[package]
name = "livp-to-jpg"
version = "0.1.0"
edition = "2021"
authors = ["Kanaricc"]
description = "Convert livp to jpg"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
libheif-rs = "0.20.0"
zip = "0.6.6"
