name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libde265-dev -y
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: strukturag/libheif
        path: libheif
    - name: Compile libheif
      run: |
        cd libheif
        mkdir build
        cmake --preset=release ..
        make
        make install
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
